services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/app
      - ./public:/usr/src/app/public
      - ./actions:/usr/src/app/actions
    command: yarn run dev
