services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run dev
